# Generated by Django 4.1 on 2022-08-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_shared', '0003_restaurantpublic_remove_restauranttype_menu'),
        ('restaurant_tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_public',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant_shared.restaurantpublic'),
        ),
    ]
