# Generated by Django 4.1 on 2022-08-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(related_name='menu', to='restaurant_tenant.category'),
        ),
    ]
