# Generated by Django 4.1 on 2022-08-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttype',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_shared.menu'),
        ),
    ]
