# Generated by Django 4.1 on 2022-08-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_shared', '0002_alter_restauranttype_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='restauranttype',
            name='menu',
        ),
    ]
