# Generated by Django 4.1 on 2022-08-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tenant', '0002_remove_restaurant_menu_and_more'),
        ('restaurant_shared', '0003_restaurantpublic_remove_restauranttype_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantType',
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant_shared.restaurantpublic'),
        ),
    ]
